name: Full build

on:
  schedule:
    - cron: 0 3 * * 0
  workflow_dispatch:

jobs:
  get-data-from-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: sudo apt-get update && apt-get install -y git
      - run: yarn install --frozen-lockfile
      - run: yarn run build:full
        env:
          GH_API_USERNAME: ${{secrets.GH_API_USERNAME}}
          GH_API_TOKEN: ${{secrets.GH_API_TOKEN}}
      - run: git config --global user.name "Tooling Builder"
      - run: git config --global user.email "tooling@openapis.org"
      - run: |
          git commit -m "chore: Updates to OpenAPI tooling source data" docs/tools.yaml
          git push origin main
